### ISSUE TITLE
Mobster no longer starts up

### ISSUE THREAD

**Issue by steverb1** [dillonkearns/mobster#49] opened 2017-06-01 20:00 UTC
After installing some Windows updates on our computer, Mobster no longer runs.  :(

Attached is the log.
[2017-06-01T19_51_07_694Z-debug.log.txt](https://github.com/dillonkearns/mobster/files/1045896/2017-06-01T19_51_07_694Z-debug.log.txt)

We are running Windows 7 Enterprise, Service Pack 1.

**Comment by dillonkearns** [comment] 2017-06-02 13:16
@steverb1 thanks for reporting the issue.

It looks like your trying to build and run this yourself from the command line, rather than downloading from the [Releases page](https://github.com/dillonkearns/mobster/releases). Can you confirm?

If that's the case, is your goal to contribute changes or use the app? If you're just trying to run the app, I would recommend downloading the `.exe`.

**Comment by steverb1** [comment] 2017-06-02 15:04
We downloaded the .exe and were using it quite successfully for several weeks.  I only downloaded the source after the .exe quite working - I resorted to running from the command line just to see if I could figure out what was wrong.
I also uninstalled and downloaded the latest .exe.  It still won't start up.

**Comment by dillonkearns** [comment] 2017-06-02 15:11
Got it, thank you for the clarification. I suspect that the logs from running the app locally don't reflect the actual issue.

Could you elaborate a little on what happens? Does the app start then crash? Run but screen doesn't show? Get uninstalled and you can't find the exe?

Windows may have some issues around marking 3rd-party exe's as viruses. Seems like that's the type of thing that could happen after a Windows update.

I'd love to get to the bottom of this. Thanks for taking the time to report this.

**Comment by steverb1** [comment] 2017-06-02 15:58
It runs but the screen doesn't show.  The mobster icon is on the task bar.  When I click it, I even see the window maximize/minimize animations.  When it is maximized we don't see any Mobster screen, but cannot click the mouse or type (like the behavior when the timer has run out and Mobster takes over the monitor, so that kind of makes sense).  When it is minimized we can use the mouse and keyboard again.

**Comment by steverb1** [comment] 2017-06-02 15:59
And Mobster is listed in the Task Manager, under Applications.

**Comment by steverb1** [comment] 2017-06-02 16:21
Could it be some issue with the transparency of the window?  We are running on a big display (for mobbing!).  It is a Vizio 55 inch 4K TV monitor.  Our resolution is set to 1920x1080, with a refresh rate of 60 Hz.  We just tried several different refresh rates, with no difference in the problem.

**Comment by dillonkearns** [comment] 2017-06-02 16:31
@steverb1 it might be related to this Electron issue: https://github.com/electron/electron/issues/9357. Could you try this custom build and let me know if you experience the issue or not (I just commented [this line](https://github.com/dillonkearns/mobster/blob/master/main.js#L183) out)?

[Custom build without transparency](https://app.box.com/s/1gl5dr0xk9wjfk1jh0is9adjdwydu216)

**Comment by steverb1** [comment] 2017-06-02 16:44
Now the main window is visible; however the countdown window is messed up, we can see part of the window but not the timer; also when mobster pops up for next person, it's not maximized. This is definitely better and we appreciate your prompt response.

**Comment by dillonkearns** [comment] 2017-06-02 16:54
@steverb1 that is great that we honed in on the issue!

[Here's a new build](https://app.box.com/s/sdz47vmsleelqf3zotfmgj7fccyhzsc0) using the workaround suggested in the electron issue (for both the main window and the timer window). Could you try this one out?

It's possible that this works with no issues now. If so then I will publish this in the next official release.

**Comment by steverb1** [comment] 2017-06-06 16:27
Well, we are still seeing the same behavior, with the above workaround build.

**Comment by dillonkearns** [comment] 2017-06-07 10:28
@steverb1 any way I could get a screenshot of the problems you described? I'm traveling this week, but will attempt to reproduce it on a Windows machine when I'm back home.

**Comment by steverb1** [comment] 2017-06-07 15:09
OK, here are a couple of screenshots.  The first is just after Mobster starts up.  It behaves like the application is waiting for us to hit "start mobbing" (or whatever that button says) but of course we don't see anything.  Also can't use the mouse or keyboard.  I'm assuming the Mobster window is there, but is transparent (?).
The second is after I click on the Mobster icon in the task bar.  Immediately after the mouse click we see the outline of a window minimizing itself into the Mobster icon on the task bar.  After that mouse clicks and the keyboard work as normal.
Sorry- there really isn't much to see.
![mobster1](https://user-images.githubusercontent.com/20443323/26885855-a335fc3e-4b58-11e7-8bed-1fa0796b880c.png)
![mobster2](https://user-images.githubusercontent.com/20443323/26885863-a684ae26-4b58-11e7-85a3-adb864e02092.png)

**Comment by dillonkearns** [comment] 2017-06-08 22:36
@steverb1 thanks so much for the detailed reports. I believe that the Electron issue I referenced above is the root problem here unfortunately. Hopefully they will come up with a fix soon.

Here's a build that removes transparency from both the main and timer windows. I think this should fix your problem, but I'm not sure if it will work well for your team to not have any transparency in the timer window. Let me know what you think, if it's acceptable then I could possibly build in an option to use this workaround to the mainline releases. Would love to hear your feedback!

[Workaround build (no transparency)](https://app.box.com/s/etnobsn9y9cnvhy9kck92eama8djt5og)

**Comment by steverb1** [comment] 2017-06-19 16:42
OK, I tried the above Workaround build.  After the installation, I ran it and it worked fine, once.  Then after exiting and running again, it was back to the same problem - couldn't see the mobster window at all.  How strange is that?  I even uninstalled and reinstalled the Workaround build fresh.  But same thing - worked once, than not after that.

**Comment by steverb1** [comment] 2017-06-19 16:44
Oh, I might know what is going on.  Does it automatically update when a new version comes out?  I saw the date on the executable change after I quit.  I think it runs the first time, then gets an update (where the transparency is not removed) and doesn't work after that.

**Comment by steverb1** [comment] 2017-06-19 16:45
One other note on the Workaround build (in case you are going to make this fix permanent).  When it first starts up it is full screen.  After the first person's turn is over and it comes up again, it is a small window.  You have to scroll around (or make the window bigger) just to see the "Continue" button.

**Comment by dillonkearns** [comment] 2017-06-24 16:05
@steverb1 yes, that's exactly right, it will update when you close and restart the application if a new version is available.

I added a flag in the latest mainline build ([0.0.37](https://github.com/dillonkearns/mobster/releases)) that has an option to disable transparency. This way it won't get messed up with auto updates (and you can get the latest updates as they come in). I hope this works out well for you and your team!

The instructions to disable transparency [are now in the README](https://github.com/dillonkearns/mobster/blob/master/README.md#workaround-for-windows-10-transparency-issues).

> One other note on the Workaround build (in case you are going to make this fix permanent). When it first starts up it is full screen. After the first person's turn is over and it comes up again, it is a small window. You have to scroll around (or make the window bigger) just to see the "Continue" button.

Thanks for reporting this. I opened up a separate issue (#50) to track this. I'd like to get to the bottom of this as well.

Keep the feedback and ideas coming, it is extremely helpful. I wouldn't have been able to get to the bottom of this issue without your help, and I'm very grateful for your detailed reports. Thank you!

I'm closing this for now. Let me know if there are any issues, or if there's anything else I can do to improve this for you!

**Closed by dillonkearns** 2017-06-24 16:05 UTC

**Comment by steverb1** [comment] 2017-06-27 21:49
OK, we've installed 0.0.37, used the option to disable transparency, and we are back in business.  Thanks!
And we appreciate you looking into issue #50 as well.

**Comment by dillonkearns** [comment] 2017-06-27 22:14
Great news! Thanks for the update.
